### ISSUE TITLE
wifi dongle stalls

### ISSUE THREAD

**Issue by vallettea** [anthill/6brain#56]
After a long time monitoring, I noticed that sometimes the wifi dongle doesn't blink anymore and and that the wifi count is zero.

Nothing weird on the journal:

```
Dec 01 17:36:48 ant2 systemd[1]: Started 6brain.service.
Dec 01 17:36:50 ant2 6brain[2979]: ============== sleeping ==============
Dec 01 17:36:50 ant2 6brain[2979]: bluetooth state : uninitialized
Dec 01 17:36:53 ant2 6brain[2979]: Tue, 01 Dec 2015 17:36:53 GMT body-parser deprecated undefined extended: provide extended option at home/pi/6brain/node_modules/6bin/js/server/
Dec 01 17:36:54 ant2 6brain[2979]: Server running on http://localhost:3000
Dec 01 17:36:54 ant2 6brain[2979]: connected to the server. ID : 89332401000001798152
Dec 01 17:36:54 ant2 6brain[2979]: data received : init 300 7 17 destination undefined
Dec 01 17:36:54 ant2 6brain[2979]: data received : init 300 7 17 destination undefined
Dec 01 17:36:58 ant2 6brain[2979]: UPDATE_BIN is valid, => 6brain
Dec 01 17:36:58 ant2 6brain[2979]: data received : {"isSuccessful":true,"index":4} destination 6bin
Dec 01 17:36:58 ant2 6brain[2979]: { isSuccessful: true, index: 4 }
Dec 01 17:36:58 ant2 6brain[2979]: transfering from main.ts
Dec 01 17:36:59 ant2 6brain[2979]: UPDATE_BIN is valid, => 6brain
Dec 01 17:36:59 ant2 6brain[2979]: data received : {"isSuccessful":true,"index":5} destination 6bin
Dec 01 17:36:59 ant2 6brain[2979]: { isSuccessful: true, index: 5 }
Dec 01 17:36:59 ant2 6brain[2979]: transfering from main.ts
Dec 01 17:37:14 ant2 6brain[2979]: UPDATE_BIN is valid, => 6brain
Dec 01 17:37:14 ant2 6brain[2979]: data received : {"isSuccessful":true,"index":6} destination 6bin
Dec 01 17:37:14 ant2 6brain[2979]: { isSuccessful: true, index: 6 }
Dec 01 17:37:14 ant2 6brain[2979]: transfering from main.ts
Dec 02 00:00:00 ant2 6brain[2979]: Sending trajectories
Dec 02 00:00:00 ant2 6brain[2979]: uncaught [TypeError: Object [object Object] has no method 'getTrajectories'] TypeError: Object [object Object] has no method 'getTrajectories'
Dec 02 00:00:00 ant2 6brain[2979]: at Job.job (/home/pi/6brain/index.js:91:33)
Dec 02 00:00:00 ant2 6brain[2979]: at Job.invoke (/home/pi/6brain/node_modules/node-schedule/lib/schedule.js:134:10)
Dec 02 00:00:00 ant2 6brain[2979]: at null._onTimeout (/home/pi/6brain/node_modules/node-schedule/lib/schedule.js:400:11)
Dec 02 00:00:00 ant2 6brain[2979]: at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
Dec 02 00:00:00 ant2 systemd[1]: 6brain.service holdoff time over, scheduling restart.
Dec 02 00:00:00 ant2 systemd[1]: Stopping 6brain.service...
Dec 02 00:00:00 ant2 systemd[1]: Starting 6brain.service...
Dec 02 00:00:00 ant2 systemd[1]: Started 6brain.service.
Dec 02 00:00:02 ant2 6brain[3560]: ============== sleeping ==============
Dec 02 00:00:02 ant2 6brain[3560]: bluetooth state : uninitialized
Dec 02 00:00:05 ant2 6brain[3560]: Wed, 02 Dec 2015 00:00:05 GMT body-parser deprecated undefined extended: provide extended option at home/pi/6brain/node_modules/6bin/js/server/
Dec 02 00:00:05 ant2 6brain[3560]: Server running on http://localhost:3000
Dec 02 00:00:05 ant2 6brain[3560]: connected to the server. ID : 89332401000001798152
Dec 02 00:00:06 ant2 6brain[3560]: data received : init 300 7 17 destination undefined
Dec 02 07:00:00 ant2 6brain[3560]: Restarting measurements.
Dec 02 07:00:00 ant2 6brain[3560]: Activating Monitor mode... interface : wlan0
Dec 02 07:00:00 ant2 6brain[3560]: physical interface to use : phy3
Dec 02 07:00:01 ant2 6brain[3560]: Exiting sleeping state
Dec 02 07:00:01 ant2 6brain[3560]: ============== monitoring ==============
Dec 02 07:00:01 ant2 6brain[3560]: Starting recording process...
Dec 02 07:00:01 ant2 6brain[3560]: tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
Dec 02 07:00:01 ant2 6brain[3560]: listening on wlan0mon, link-type IEEE802_11_RADIO (802.11 plus radiotap header), capture size 262144 bytes
Dec 02 07:00:01 ant2 6brain[3560]: Exiting monitoring state
Dec 02 07:00:01 ant2 6brain[3560]: ============== recording ==============
Dec 02 07:05:01 ant2 6brain[3560]: wifi measurements received
Dec 02 07:10:01 ant2 6brain[3560]: wifi measurements received
Dec 02 07:15:01 ant2 6brain[3560]: wifi measurements received
```

though there has been a restart due to an error.
The physical interface is the right one:

```
pi@ant2 ~ $ ((iw dev | head -n 1 | sed s/#// | grep phy) || (iw phy | head -n 1 | sed "s/Wiphy //" | grep phy))
phy3
pi@ant2 ~ $ (iw phy | head -n 1 | sed "s/Wiphy //" | grep phy)
phy3
pi@ant2 ~ $ (iw dev | head -n 1 | sed s/#// | grep phy)
phy3
```

and 

```
pi@ant2 ~ $ ifconfig
eth0      Link encap:Ethernet  HWaddr b8:27:eb:c3:e9:2a
          inet addr:10.33.0.68  Bcast:10.33.1.255  Mask:255.255.254.0
          inet6 addr: fe80::ba27:ebff:fec3:e92a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:140111 errors:0 dropped:0 overruns:0 frame:0
          TX packets:40242 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:28955950 (27.6 MiB)  TX bytes:5897658 (5.6 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:8141 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8141 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1218686 (1.1 MiB)  TX bytes:1218686 (1.1 MiB)

wlan0mon  Link encap:UNSPEC  HWaddr C4-E9-84-1C-43-F6-30-30-00-00-00-00-00-00-00-00
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4668931 errors:0 dropped:4618818 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1279265946 (1.1 GiB)  TX bytes:0 (0.0 B)
```

**Comment by vallettea** [comment]
When i launch tcpdump by hand nothing comes out of it:

```
pi@ant2 ~ $ sudo tcpdump -I -e -q -t -U -i wlan0mon
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on wlan0mon, link-type IEEE802_11_RADIO (802.11 plus radiotap header), capture size 262144 bytes
```

**Comment by vallettea** [comment]
the verbose mode give an hint:

```
pi@ant2 ~ $ sudo tcpdump -I -e -q -t -U -i -v wlan0mon
tcpdump: -v: No such device exists
(-v: SIOCGIWPRIV: No such device)
```

**Comment by vallettea** [comment]
shit I haven't noticed that -v was not properly placed in the previous command and i restarted the interface with:

```
pi@ant2 ~ $ sudo iw dev wlan0mon del
pi@ant2 ~ $ sudo iw phy phy3 interface add wlan0mon type monitor
pi@ant2 ~ $ sudo ifconfig wlan0mon up
```

the led is blinking and the tcpdump command now outputs all what's needed.

I have to wait until the dongle stalls again to see the output a a verbose tcpdump again.
